### ISSUE TITLE
Crashes on 1.16.5

### ISSUE THREAD

**Issue by tildejustin** [mjtb49/DragonFightPathVisualizer#2]
I don't know if support for this version is intended, but the readme says 1.16.x so I would assume so.
Anyways, log if it is:
```
MultiMC version: 0.6.16-3431


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.67.58.35, 18.67.58.44, 18.67.58.60, 18.67.58.61]

session.minecraft.net resolves to:
    [35.153.153.200, 34.197.32.8, 100.24.172.95]

textures.minecraft.net resolves to:
    [2620:1ec:40::40, 2620:1ec:49::40, 13.107.238.40, 13.107.237.40]

api.mojang.com resolves to:
    [18.160.41.65, 18.160.41.112, 18.160.41.80, 18.160.41.21]


Minecraft folder is:
C:/MultiMC/instances/1.16.5_dragon/.minecraft


Java path is:
D:/Program Files/Eclipse Adoptium/jdk-8.0.352.8-hotspot/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_352, using 64-bit architecture, from Temurin.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/MultiMC/instances/1.16.5_dragon/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/MultiMC/libraries/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
  C:/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  C:/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  C:/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/MultiMC/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  C:/MultiMC/libraries/net/fabricmc/fabric-loader/0.14.12/fabric-loader-0.14.12.jar
  C:/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] dragon-fight-visualizer-1.6

Params:
  --username  --version 1.16.5 --gameDir C:/MultiMC/instances/1.16.5_dragon/.minecraft --assetsDir C:/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 4328


Using onesix launcher.

ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
[22:40:17] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.12
[22:40:17] [main/INFO]: Loading 4 mods:
	- dragon_fight_visualizer 1.6
	- fabricloader 0.14.12
	- java 8
	- minecraft 1.16.5
[22:40:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:40:22] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:40:23] [Render thread/INFO]: Setting user: tildejustin
[22:40:23] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[22:40:26] [Render thread/INFO]: Narrator library for x64 successfully loaded
[22:40:26] [Render thread/INFO]: Reloading ResourceManager: Default
[22:40:28] [Render thread/INFO]: OpenAL initialized.
[22:40:28] [Render thread/INFO]: Sound engine started
[22:40:29] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[22:40:29] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[22:40:29] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:40:29] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:40:29] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:40:29] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:40:29] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:40:29] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[22:40:29] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:40:29] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:41:52] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[22:41:52] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:41:52] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:41:52] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[22:41:52] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:41:52] [Render thread/INFO]: Reloading ResourceManager: Default
[22:41:52] [Render thread/INFO]: Loaded 7 recipes
[22:41:53] [Render thread/INFO]: Loaded 927 advancements
[22:41:53] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:41:53] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[22:41:53] [Server thread/INFO]: Generating keypair
[22:41:56] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:41:56] [Render thread/INFO]: Preparing spawn area: 0%
[22:41:57] [Render thread/INFO]: Preparing spawn area: 0%
[22:41:57] [Render thread/INFO]: Preparing spawn area: 1%
[22:41:58] [Render thread/INFO]: Preparing spawn area: 4%
[22:41:58] [Render thread/INFO]: Preparing spawn area: 9%
[22:41:59] [Render thread/INFO]: Preparing spawn area: 13%
[22:41:59] [Render thread/INFO]: Preparing spawn area: 19%
[22:42:00] [Render thread/INFO]: Preparing spawn area: 23%
[22:42:00] [Render thread/INFO]: Preparing spawn area: 26%
[22:42:01] [Render thread/INFO]: Preparing spawn area: 32%
[22:42:01] [Render thread/INFO]: Preparing spawn area: 36%
[22:42:02] [Render thread/INFO]: Preparing spawn area: 44%
[22:42:02] [Render thread/INFO]: Preparing spawn area: 49%
[22:42:03] [Render thread/INFO]: Preparing spawn area: 55%
[22:42:03] [Render thread/INFO]: Preparing spawn area: 60%
[22:42:04] [Render thread/INFO]: Preparing spawn area: 68%
[22:42:04] [Render thread/INFO]: Preparing spawn area: 73%
[22:42:05] [Render thread/INFO]: Preparing spawn area: 81%
[22:42:05] [Render thread/INFO]: Preparing spawn area: 87%
[22:42:06] [Render thread/INFO]: Preparing spawn area: 94%
[22:42:06] [Render thread/INFO]: Time elapsed: 9894 ms
[22:42:06] [Server thread/INFO]: Changing view distance to 15, from 10
[22:42:07] [Server thread/INFO]: tildejustin[local:E:e928e17c] logged in with entity id 292 at (-7.5, 63.0, 254.5)
[22:42:07] [Server thread/INFO]: tildejustin joined the game
[22:42:08] [Render thread/INFO]: [CHAT] Loaded Dragon Fight Visualizer
[22:42:08] [Server thread/INFO]: Saving and pausing game...
[22:42:08] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:42:08] [Render thread/INFO]: Loaded 0 advancements
[22:42:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:42:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:42:23] [Server thread/INFO]: [tildejustin: Changed the block at -8, 63, 254]
[22:42:23] [Render thread/INFO]: [CHAT] Changed the block at -8, 63, 254
[22:42:23] [Server thread/INFO]: tildejustin has made the advancement [The End?]
[22:42:23] [Server thread/INFO]: Saving and pausing game...
[22:42:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:42:23] [Render thread/INFO]: [CHAT] tildejustin has made the advancement [The End?]
[22:42:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:42:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:42:24] [Render thread/INFO]: Loaded 15 advancements
[22:42:25] [Server thread/INFO]: Scanning for legacy world dragon fight...
[22:42:25] [Server thread/INFO]: Found that the dragon has not yet been killed in this world.
[22:42:26] [Server thread/INFO]: [CHAT] Dragon now headed counterclockwise (looking down)
[22:42:26] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: net.minecraft.class_11.method_19314()Ljava/util/List;
	at matthewbolan.enderdragonpaths.render.PathRenderer.render(PathRenderer.java:61) ~[dragon-fight-visualizer-1.6.jar:?]
	at matthewbolan.enderdragonpaths.render.PathRenderer.render(PathRenderer.java:52) ~[dragon-fight-visualizer-1.6.jar:?]
	at matthewbolan.enderdragonpaths.render.RendererGroup.render(RendererGroup.java:35) ~[dragon-fight-visualizer-1.6.jar:?]
	at matthewbolan.enderdragonpaths.DragonFightDebugger.lambda$onInitialize$0(DragonFightDebugger.java:65) ~[dragon-fight-visualizer-1.6.jar:?]
	at matthewbolan.enderdragonpaths.render.RenderQueue.lambda$onRender$0(RenderQueue.java:49) ~[dragon-fight-visualizer-1.6.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_352]
	at matthewbolan.enderdragonpaths.render.RenderQueue.onRender(RenderQueue.java:49) ~[dragon-fight-visualizer-1.6.jar:?]
	at net.minecraft.class_3694.handler$zzg000$swap(class_3694.java:515) ~[client-intermediary.jar:?]
	at net.minecraft.class_3694.method_15405(class_3694.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:750) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:546) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[22:42:27] [Server thread/INFO]: Stopping server
[22:42:27] [Server thread/INFO]: Saving players
[22:42:27] [Server thread/INFO]: tildejustin lost connection: Disconnected
[22:42:27] [Server thread/INFO]: tildejustin left the game
[22:42:27] [Server thread/INFO]: Stopping singleplayer server as player logged out
[22:42:27] [Server thread/INFO]: Saving worlds
[22:42:27] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:42:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[22:42:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:42:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:42:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:42:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:42:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[22:42:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:42:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/27/22 10:42 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_11.method_19314()Ljava/util/List;
	at matthewbolan.enderdragonpaths.render.PathRenderer.render(PathRenderer.java:61)
	at matthewbolan.enderdragonpaths.render.PathRenderer.render(PathRenderer.java:52)
	at matthewbolan.enderdragonpaths.render.RendererGroup.render(RendererGroup.java:35)
	at matthewbolan.enderdragonpaths.DragonFightDebugger.lambda$onInitialize$0(DragonFightDebugger.java:65)
	at matthewbolan.enderdragonpaths.render.RenderQueue.lambda$onRender$0(RenderQueue.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at matthewbolan.enderdragonpaths.render.RenderQueue.onRender(RenderQueue.java:49)
	at net.minecraft.class_3694.handler$zzg000$swap(class_3694.java:515)
	at net.minecraft.class_3694.method_15405(class_3694.java)
	at net.minecraft.class_757.method_3188(class_757.java:750)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at matthewbolan.enderdragonpaths.render.PathRenderer.render(PathRenderer.java:61)
	at matthewbolan.enderdragonpaths.render.PathRenderer.render(PathRenderer.java:52)
	at matthewbolan.enderdragonpaths.render.RendererGroup.render(RendererGroup.java:35)
	at matthewbolan.enderdragonpaths.DragonFightDebugger.lambda$onInitialize$0(DragonFightDebugger.java:65)
	at matthewbolan.enderdragonpaths.render.RenderQueue.lambda$onRender$0(RenderQueue.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at matthewbolan.enderdragonpaths.render.RenderQueue.onRender(RenderQueue.java:49)
	at net.minecraft.class_3694.handler$zzg000$swap(class_3694.java:515)
	at net.minecraft.class_3694.method_15405(class_3694.java)
	at net.minecraft.class_757.method_3188(class_757.java:750)

-- Affected level --
Details:
	All players: 1 total; [class_746['tildejustin'/292, l='ClientLevel', x=100.50, y=49.00, z=0.50]]
	Chunk stats: Client Chunk Cache: 1369, 225
	Level dimension: minecraft:the_end
	Level spawn location: World: (-16,63,256), Chunk: (at 0,3,0 in -1,16; contains blocks -16,0,256 to -1,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 386 game time, 386 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_352, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 503839720 bytes (480 MB) / 1149763584 bytes (1096 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 527.56, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor 
#@!@# Game crashed! Crash report saved to: #@!@# C:\MultiMC\instances\1.16.5_dragon\.minecraft\crash-reports\crash-2022-12-27_22.42.29-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 27 Dec 2022 22:42:31 -0500

```

**Comment by tildejustin** [comment]
also happens with java 19 and fabric 1.10.5
